name: smart_cluster_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.1
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.0.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  flutter_typeahead: ^4.3.7
  google_fonts: ^6.1.0
  logging: ^1.2.0
  intl: ^0.20.2
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.3
  shared_preferences: ^2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  flutter_keyboard_visibility: 5.3.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo.png
